---
title: "R Notebook"
output: html_notebook
---

Aritmetica en R

```{r}
3+5   #prueba
6+10

5-1
5*2
(5-2)/2
2^5
28%%6

```
Asignacion de variables
```{r}
x = 10
y <- 20

total = x+y
total
```

tipos de datos
```{r}
my_character <- "hola mundo"
my_logical <- FALSE

```

```{r}
class (my_character)
class (my_logical)
```
```{r}
my_character <- "mundo"
```

Vectores
```{r}
numeric_vector <- c(1, 10, 49)
numeric_vector
character_vector <- c("a","b","c")
boolean_vector <- c(TRUE, FALSE, TRUE)
character_vector
boolean_vector
```
Nombrando un vector
```{r}
poker_vector <- c(140, -50, 20, -122 , 240)
roulette_vector <- c(-25, 50, 100, -340, 10)
names (poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector
names(roulette_vector)<- c("Monday","Tuesday","Wednesday","Thursday","Friday")
roulette_vector
```
Comparando y seleccionando
```{r}
age <- 17
age >= 18

result <- age >= 18
result

A_vector <- c(1,2,3)
B_Vector <- c(4,5,6)

total_vector <- A_vector - B_Vector
total_vector

total_daily <- poker_vector+roulette_vector
total_daily

total_poker <- sum(poker_vector)
total_poker

total_roulette <- sum(roulette_vector)

sum_total <- total_poker + total_roulette
sum_total


poker_vector
poker_vector [1]

poker_vector [c(2,3,4)]

roulette_vector [2:5]

poker_vector [c("Monday","Tuesday","Wednesday")]

poker_start <- poker_vector [c("Monday","Tuesday","Wednesday")]

mean (poker_start)

selection_vector <- poker_vector >0

poker_winning_days <- poker_vector [selection_vector]
poker_winning_days

```

Matrices

```{r}
matrix (1:9, byrow = TRUE, nrow = 3)

matrix (1:9, byrow = FALSE, nrow = 3)

matrix (1:9, byrow = TRUE, nrow = 3)
```

```{r}
new_hope <- c(460.998, 314.4)
empire_strike <- c(2980.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strike, return_jedi)
box_office


star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow = 3)
star_wars_matrix

region <- c("US", "Non-US")
titles <- c("A new hope", "The Empire Strikes Back", "Return of the Jedi")

colnames (star_wars_matrix) <- region
rownames (star_wars_matrix) <- titles

star_wars_matrix
```
row sums

```{r}

worldwide_vector  <- rowSums(star_wars_matrix)
star_wars_matrix
worldwide_vector

all_wars_variable <- cbind(star_wars_matrix,worldwide_vector)
all_wars_variable

worldwide_cols <- colSums(all_wars_variable)
worldwide_cols

all_wars_variable <- rbind (all_wars_variable, worldwide_cols)
all_wars_variable
```
selection of matrix elements
```{r}

non_US_all <- all_wars_variable[,2]
non_US_all

mean(non_US_all)

non_US_all <- all_wars_variable[1:3,2]
mean(non_US_all)

```

Arithmetic with matrix

O
```{r}
us_all <- all_wars_variable[1:3,1]
us_all <- us_all *0.2
us_all

```
Factors

```{r}
sex_vector <- c("Male", "Female", "Male", "Female")

factor_sex_vector <- factor(sex_vector)

factor_sex_vector


temperature_vector <- c("High", "Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector, order=TRUE, levels=c("Low","Medium","High"))

factor_temperature_vector
```
Factor leves
```{r}
survey_vector <- c("M", "F","F", "M","M")

factor_survey_vector <- factor(survey_vector)
factor_survey_vector

levels(factor_survey_vector) <- c("Female","Male")
factor_survey_vector
```

Summary
```{r}

summary(survey_vector)
summary(factor_survey_vector)

male <- factor_survey_vector[1]
male

female <- factor_survey_vector[2]
female

male > female

speed_vector <- c("medium", "slow","slow","medium","fast")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels = c("slow", "medium", "fast"))
factor_speed_vector

da2 <- factor_speed_vector[2]
da3 <- factor_speed_vector[1]
da2
da3

da2<da3
da2>da3

```


