---
title: "R Notebook"
output: html_notebook
---

Functions

```{r}
pow_two<- function (x, print_info=TRUE){
  y<- x^2
  if (print_info == TRUE)
  {
    print (paste(x, "to the power two equals", y))
  }
  return (y)
}

result <- pow_two(3)
result
```

Function scoping

```{r}
pow_two <- function (x){
  y <- x ^ 2
  return (y)
}

pow_two(4)
y
x

```

R passes arguments sby value

```{r}

triple <- function (x){
  x <- 3*x
  x
}

a<- 5

triple (a)

a


```
Other types of parameters

```{r}

linkedin

interpret <- function(num_views){
  if (num_views>15){
    print ("you are popular!")
    return (num_views)
  }else{
    print ("try to be more visible")
    return (0)
  }
}

interpret (linkedin[1])

interpret_all <- function (views, return_sum=TRUE){
  count<- 0
  for(v in views){
    count <- count + interpret(v)
  }
  
  if (return_sum==TRUE){
    return (count)
    
  }else {
    return(NULL)
  }
}


interpret_all(linkedin)
```


Load a R package

```{r}


library(ggplot2)

qplot (mtcars$wt, mtcars$hp)
```



Using apply in R

lapply

```{r}



temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

vector <- c(3,7,9,6,1)

select <- function(x){
  print (paste("This collection contains total = ", sum(x)))
}

lapply(temp, min)

list <- lapply (vector, select)

for (t in temp){
  print (min(t))
}

```
Lapply and anonymous functions

```{r}
(function (x) {3*x})(9)

pioneers <- c("GAUSS:1777","BAYES:1702","PASCAL:1623", "PEARSON:1857")
split <- strsplit (pioneers, split = ":")
split

split_low <- lapply (split, tolower)
split_low <- lapply (split, toupper)
split_low

names <- lapply (split_low, function(x){x[1]})
names

years <- lapply (split_low, function (x){x[2]})
years
```

use lapply with additional arguments

```{r}

select_el <- function(x, index){
  x[index]
}

names <- lapply (split_low, select_el, 1)

names

years <- lapply (split_low, select_el, 2)
years
```

Sapply

```{r}

extremes <- function (x){
  c(min = min(x), max=max(x))
}

lapply(temp, extremes)
sapply(temp, extremes)


temp2 <- list (1,2,3,4,5)

func_temp2 <- function (x){

  x
}

lapply (temp2, func_temp2)
sapply (temp2, func_temp2)

```

Vapply

```{r}

basics <- function (x)
  
{
  c(min=max(x), mean=mean(x), max=max(x))
  
}

lapply(temp, basics)
sapply(temp, basics)
vapply(temp, basics,numeric(3))

temp3 <- c("Guatemala", "Salvador","Honduras", "Nicaragua")

unique_letters <- function (name){
  bane <- gsub(" ", "", name)
  letters <- strsplit(name, split="")[[1]]
  unique (letters)
}

lapply (temp3, unique_letters)
sapply (temp3, unique_letters)
vapply (temp3, unique_letters, nchar(7))

```



utilities

```{r}

errors <- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)

print (sum(abs(round(errors))))

?round

linkedin
facebook

li_vec <- unlist(linkedin)
fb_vec <- unlist(facebook)

li_vec

fb_vec

social_vec <- append (li_vec, fb_vec)
social_vec

sort(social_vec, decreasing=TRUE)

```

GREP & GREPL

```{r}


emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org","invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")


grepl(pattern="edu", emails)

hits<-grep (patter="edu", x=emails)

emails[hits]
```

